### ISSUE TITLE
播放萤石云提供的flv格式视频，直接报错了

### ISSUE THREAD

**Issue by xskjs888** [Ezviz-OpenBiz/EZUIKit-flv#5]
![image](https://github.com/Ezviz-OpenBiz/EZUIKit-flv/assets/22831759/59a5653c-cf92-4323-9a1f-2c4ddc63b4ff)

**Comment by freeshineit** [comment]
> ![image](https://private-user-images.githubusercontent.com/22831759/335146903-59a5653c-cf92-4323-9a1f-2c4ddc63b4ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczNTMwNDIsIm5iZiI6MTcxNzM1Mjc0MiwicGF0aCI6Ii8yMjgzMTc1OS8zMzUxNDY5MDMtNTlhNTY1M2MtY2Y5Mi00MzIzLTlhMWYtMmM0ZGRjNjNiNGZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAyVDE4MjU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkM2I3NDZhMDdiNjQ4YmQyNDYwNmNkYzI4OWRjNzZhYmIwNmUyMTExNzQ0MjM4MTJhYjU4YTNmNGIxNWM3OWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qTVXHvZk2P4nd2IWdb10AzLcjhHw0VirGPm2BntAbYk)

你好 可以提供一下  浏览器的版本吗
