### ISSUE TITLE
怎么关闭日志上传

### ISSUE THREAD

**Issue by qq497495160** [Ezviz-OpenBiz/EZUIKit-flv#9]
"vue": "2.6.12",

    "ezuikit-flv": "^1.0.0"

在进行接口上传时，如出现报错，会导致日志，含token被上传到 “https://log.ys7.com/statistics.do/opensdk_ezuikit”，很影响安全性，是否有开关关闭？

**Comment by freeshineit** [comment]
????

**Comment by qq497495160** [comment]
提交错了，请帮忙删除该issue，非常感谢~

**Comment by freeshineit** [comment]
自己关闭就可以了
